version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: sqlx-repository-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sqlx_repository_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./crates/sqlx-repository/tests/fixtures:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  postgres_test:
    image: postgres:15-alpine
    container_name: sqlx-repository-postgres-test
    restart: "no"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sqlx_repository_test
    ports:
      - "5433:5432"
    tmpfs:
      - /var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 2s
      retries: 10

  mysql:
    image: mysql:8.0
    container_name: sqlx-repository-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: sqlx_repository_dev
      MYSQL_USER: sqlx
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-ppassword"]
      interval: 5s
      timeout: 5s
      retries: 5

  mysql_test:
    image: mysql:8.0
    container_name: sqlx-repository-mysql-test
    restart: "no"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: sqlx_repository_test
      MYSQL_USER: sqlx
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    tmpfs:
      - /var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-ppassword"]
      interval: 2s
      timeout: 2s
      retries: 10

  sqlite:
    # SQLite doesn't need a container - we'll use file-based SQLite for testing
    # This is just a placeholder for documentation
    image: alpine:latest
    container_name: sqlx-repository-sqlite-placeholder
    restart: "no"
    command: /bin/sh -c "echo 'SQLite uses file-based storage' && sleep infinity"

  # Development tools
  adminer:
    image: adminer:latest
    container_name: sqlx-repository-adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - mysql
    environment:
      ADMINER_DEFAULT_SERVER: postgres

volumes:
  postgres_data:
    driver: local
  mysql_data:
    driver: local

networks:
  default:
    name: sqlx-repository-network